name = "activelegend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[env.production]
name = "activelegend"

[env.production.vars]
ENVIRONMENT = "production"

# Functions configuration
[functions]
directory = "functions" 